SystemOrganization addCategory: #'Winter-Examples'!
SystemOrganization addCategory: 'Winter-Examples-Asteroids'!
SystemOrganization addCategory: 'Winter-Examples-FallingBall'!
SystemOrganization addCategory: 'Winter-Examples-Joints'!
SystemOrganization addCategory: 'Winter-Examples-PyramidStack'!
SystemOrganization addCategory: 'Winter-Examples-Resources'!
SystemOrganization addCategory: 'Winter-Examples-Running'!
