SystemOrganization addCategory: #'Storm-Examples'!
SystemOrganization addCategory: 'Storm-Examples-Asteroids'!
SystemOrganization addCategory: 'Storm-Examples-FallingBall'!
SystemOrganization addCategory: 'Storm-Examples-Joints'!
SystemOrganization addCategory: 'Storm-Examples-PyramidStack'!
SystemOrganization addCategory: 'Storm-Examples-Resources'!
SystemOrganization addCategory: 'Storm-Examples-Running'!
